# Configures the environmental sensor Driver

# Generates static libraries:
# - SHARC::ENV

set(STM32_HAL_ENV_DRIVER_INCLUDE_DIRECTORIES
	${CMAKE_SOURCE_DIR}/Modules/BMP280/Inc
)

file(GLOB STM32_HAL_ENV_DRIVER_SOURCES
	${CMAKE_SOURCE_DIR}/Modules/BMP280/Src/*.c
)

# BMP Driver
add_library(STM32_HAL_ENV_DRIVER STATIC
	${STM32_HAL_ENV_DRIVER_SOURCES}
)


target_include_directories(STM32_HAL_ENV_DRIVER SYSTEM
	PUBLIC ${STM32_HAL_ENV_DRIVER_INCLUDE_DIRECTORIES}
)

add_library(SHARC::ENV ALIAS STM32_HAL_ENV_DRIVER)