# Configures the RB9603 Driver

# Generates static libraries:
# - SHARC::SAT

set(STM32_HAL_SAT_DRIVER_INCLUDE_DIRECTORIES
	${CMAKE_SOURCE_DIR}/Modules/RB9603/Inc
)

file(GLOB STM32_HAL_SAT_DRIVER_SOURCES
	${CMAKE_SOURCE_DIR}/Modules/RB9603/Src/RB9603.c
)

# SD Driver
add_library(STM32_HAL_SAT_DRIVER STATIC
	${STM32_HAL_SAT_DRIVER_SOURCES}
)

target_include_directories(STM32_HAL_SAT_DRIVER SYSTEM
	PUBLIC ${STM32_HAL_SAT_DRIVER_INCLUDE_DIRECTORIES}
)

add_library(SHARC::SAT ALIAS STM32_HAL_SAT_DRIVER)